---
version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    mplog:
        class: lib.mplog.MultiProcessingLog
        level: DEBUG
        formatter: simple
        name: intrasploit.log
        mode: a
        maxsize: 52428800
        rotate: 5
root:
    level: DEBUG
    handlers: [console, mplog]
